version: '3.3'

services:

  sentinelloader:
    build: .
    image: flaviostutz/sentinelloader
    environment: 
      - COPERNICUS_USER=flaviostutz
      - COPERNICUS_PASSWORD=Through00
    volumes:
      - ./notebooks:/notebooks
      - ./sentinelloader:/notebooks/sentinelloader
    ports:
      - 8585:8888
  