version: '3.3'

services:

  sentinelloader:
    build: .
    image: flaviostutz/sentinelloader
    environment: 
      - COPERNICUS_USER=[yourusername]
      - COPERNICUS_PASSWORD=[yourpassword]
    volumes:
      - ./notebooks:/notebooks
      - ./sentinelloader:/notebooks/sentinelloader
    ports:
      - 8585:8888
  
